# a mybinder.org-ready environment for demoing jupyterlab_chat
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-chat-demo
#
name: jupyterlab-chat-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=3.1.0a13,<4.0.0a0
  # labextension build dependencies
  - nodejs >=15,<16
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
